### ISSUE TITLE
PullToRefresh

### ISSUE THREAD

**Issue by banchaowei** [engalar/mendix-pluggable-widget-PullToRefresh#1]

**Comment by banchaowei** [comment]
> _No description从微流返回数据 通过上下文和联想获取到列表对象，我需要上滑刷新触发微流调用分页查询并且保留之前的历史数据在界面（就是把第二页的数据追加到第一页的下面，以此类推），接口需要的参数就是pagesize 和pagenumber provided._

**Comment by engalar** [comment]
![image](https://user-images.githubusercontent.com/2411314/168585610-89713cf6-e940-42a3-a111-7794293de0ec.png)

我这里不存在这个问题
